### ISSUE TITLE
Task  Pages

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/The-Tarkov-Handbook#23]
### Tasks Main Page
- [ ] Update task item image for 0.13
- [ ] Update Fence link.
- [ ] Update Skier link.
- [ ] Update Peacekeeper link.
- [ ] Update Mechanic link.
- [ ] Update Ragman link.
- [ ] Update Jaeger link.

---

### Prapor
- [ ] Check, update, and add new tasks.

---

### Therapist
- [ ] Check, update, and add new tasks.

---

### Fence
- [ ] Check, update, and add new tasks.

---

### Skier
- [ ] Check, update, and add new tasks.

---

### Peacekeeper
- [ ] Check, update, and add new tasks.

---

### Mechanic
- [ ] Check, update, and add new tasks.

---

### Ragman
- [ ] Check, update, and add new tasks.

---

### Jaeger
- [ ] Check, update, and add new tasks.
