### ISSUE TITLE
General Code Updates

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/The-Tarkov-Handbook#28]
### Updates to `<head>` Section (All Pages)
- [x] Add Google Analytics to all pages.

---

### Index
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/index-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook">
<meta name="twitter:description" content="The most official-unofficial guide for Escape From Tarkov. Built for your second monitor.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/index-meta.png">
<meta property="og:description" content="The most official-unofficial guide for Escape From Tarkov. Built for your second monitor.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### AI
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/AI-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | AI">
<meta name="twitter:description" content="A full breakdown of all AI in Escape From Tarkov.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/AI-meta.webp">
<meta property="og:description" content="A full breakdown of all AI in Escape From Tarkov.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | AI">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Ammo
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Ammo-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Ammo">
<meta name="twitter:description" content="A comprehensive ammo guide for all Escape From Tarkov ammunition. NFAM ammo chart included.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Ammo-meta.jpg">
<meta property="og:description" content="A comprehensive ammo guide for all Escape From Tarkov ammunition. NFAM ammo chart included.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Ammo">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Armor
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Armor-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Armor">
<meta name="twitter:description" content="Learn what armor is, how its attributes function, and more.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Armor-meta.webp">
<meta property="og:description" content="Learn what armor is, how its attributes function, and more.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Armor">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### CKeys
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/CKeys-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Keys | Customs">
<meta name="twitter:description" content="The keys you should always keep on you when playing the map customs.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/CKeys-meta.jpg">
<meta property="og:description" content="The keys you should always keep on you when playing the map customs.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Keys | Customs">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```


---

### Customs
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Customs-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Customs">
<meta name="twitter:description" content="A high quality map of the location Customs.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Customs-meta.jpg">
<meta property="og:description" content="A high quality map of the location Customs.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Customs">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```


---

### Factory
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Factory-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Factory">
<meta name="twitter:description" content="A high quality map of the location Factory.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Factory-meta.png">
<meta property="og:description" content="A high quality map of the location Factory.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Factory">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Interchange
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Interchange-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Interchange">
<meta name="twitter:description" content="A high quality map of the location Interchange.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Interchange-meta.png">
<meta property="og:description" content="A high quality map of the location Interchange.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Interchange">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Items
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Items-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Items">
<meta name="twitter:description" content="Find the value of items on the market, calculate profit, and learn what the best keys are for any map.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Items-meta.jpg">
<meta property="og:description" content="Find the value of items on the market, calculate profit, and learn what the best keys are for any map.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Items">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Labs
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Labs-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | The Lab">
<meta name="twitter:description" content="A high quality map of the location The Lab.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Labs-meta.png">
<meta property="og:description" content="A high quality map of the location The Lab.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | The Lab">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```
---

### Lighthouse
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Lighthouse-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Lighthouse">
<meta name="twitter:description" content="A high quality map of the location Lighthouse.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Lighthouse-meta.png">
<meta property="og:description" content="A high quality map of the location Lighthouse.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Lighthouse">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Maps
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Maps-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps">
<meta name="twitter:description" content="Explore every location in Escape From Tarkov with 3D maps showing you exactly what you need to know.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Maps-meta.webp">
<meta property="og:description" content="Explore every location in Escape From Tarkov with 3D maps showing you exactly what you need to know.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Medicine
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Medicine-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Medicine">
<meta name="twitter:description" content="Explore a comprehensive medical guide of every medical item in Escape From Tarkov.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Medicine-meta.webp">
<meta property="og:description" content="Explore a comprehensive medical guide of every medical item in Escape From Tarkov.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Medicine">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Prapor
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Prapor-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Prapor">
<meta name="twitter:description" content="Learn more about Prapor, his tasks, and how to complete them. Video guides included.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Prapor-meta.webp">
<meta property="og:description" content="Learn more about Prapor, his tasks, and how to complete them. Video guides included.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Prapor">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Reserve
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Reserve-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Reserve">
<meta name="twitter:description" content="A high quality map of the location Reserve.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Reserve-meta.jpg">
<meta property="og:description" content="A high quality map of the location Reserve.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Reserve">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Rules
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Rules-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Rules">
<meta name="twitter:description" content="PVP guides, pre-raid checklists, and the hardcore season 7 ruleset. Learn how to survive in Tarkov.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Rules-meta.png">
<meta property="og:description" content="PVP guides, pre-raid checklists, and the hardcore season 7 ruleset. Learn how to survive in Tarkov.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Rules">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### SKeys (Shoreline Keys)
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/SKeys-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Keys | Shoreline">
<meta name="twitter:description" content="The keys you should always keep on you when playing the map Shoreline.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/SKeys-meta.jpg">
<meta property="og:description" content="The keys you should always keep on you when playing the map Shoreline.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Keys | Shoreline">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Settings
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Settings-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Settings Guide">
<meta name="twitter:description" content="The best settings & optimizations for Escape From Tarkov you can find on the web.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Settings-meta.png">
<meta property="og:description" content="The best settings & optimizations for Escape From Tarkov you can find on the web.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Settings Guide">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Shoreline
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Shoreline-meta.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Shoreline">
<meta name="twitter:description" content="A high quality map of the location Shoreline.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Shoreline-meta.png">
<meta property="og:description" content="A high quality map of the location Shoreline.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Shoreline">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Tasks
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Tasks-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Tasks">
<meta name="twitter:description" content="Learn more about the traders, their tasks, and how to complete them. Video guides included.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Tasks-meta.webp">
<meta property="og:description" content="Learn more about the traders, their tasks, and how to complete them. Video guides included.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Tasks">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Therapist
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Therapist-meta.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Tasks | Therapist">
<meta name="twitter:description" content="Learn more about Therapist, her tasks, and how to complete them. Video guides included.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Therapist-meta.webp">
<meta property="og:description" content="Learn more about Therapist, her tasks, and how to complete them. Video guides included.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Tasks | Therapist">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Woods
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/Woods-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Woods">
<meta name="twitter:description" content="A high quality map of the location Woods.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/Woods-meta.jpg">
<meta property="og:description" content="A high quality map of the location Woods.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Woods">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

---

### Streets
- [x] Update head tag with
```
<!-- Twitter Tags -->
<meta name="twitter:image" content="https://TheTarkovHandbook.com/assets/images/streets-meta.jpg">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="The Tarkov Handbook | Maps | Streets">
<meta name="twitter:description" content="A high quality map of the location Streets of Tarkov.">
<meta name="twitter:site" content="@TarkovHandbook">

<!-- General Tags -->
<meta property="og:image" content="https://TheTarkovHandbook.com/assets/images/streets-meta.jpg">
<meta property="og:description" content="A high quality map of the location Streets of Tarkov.">
<meta property="og:type" content="website">
<meta property="og:title" content="The Tarkov Handbook | Maps | Streets">
<meta property="og:url" content="https://thetarkovhandbook.com/">

<!-- Prevent Cache -->
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">

<!-- Embed Theme Color -->
<meta name="theme-color" content="#4b4230">
```

**Comment by DoctorSoup143** [comment]
Complete

**Comment by DoctorSoup143** [comment]
Issue not fixed. Re-attempt.

**Comment by DoctorSoup143** [comment]
Updated for next patch.
